### ISSUE TITLE
Using GDScript language server to dump script symbols

### ISSUE THREAD

**Issue by Geequlim** [GDQuest/gdscript-docs-maker#12]
The functionality of parsing GDScript symbols with documentations with javadoc liked behavior is already implemented by the GDScript language server.

I think you don't need to make another parser as you can dump all the informations to json with an editor plugin. The lsp using the original gdscript parser so it should be the best choice to do this kind of work.

To dump the script symbols to json you just need to call this api in your editor plugin

https://github.com/godotengine/godot/blob/096bf873bc44a942ba7d5c4e52bf089fda6fdd6b/modules/gdscript/language_server/gdscript_workspace.cpp#L46

**Comment by Geequlim** [comment]
The dumped json should contains constants，functions，signals and all symbols defined in script files with javadoc liked documents and signatures.
We can make a tool to render the generated json to webpage like read the doc

**Comment by NathanLovato** [comment]
Thanks, I'll check this out.

How do you write docstrings or document your GDScript code with that? Getting symbols is one thing, but what we need is to get docstrings for our own Godot GDScript projects. Just like you would in Python, having docstrings in modules and functions. Is this possible?

**Comment by NathanLovato** [comment]
Thanks, I'll check this out.

Would you have a brief usage example? I looked for a function like this in the editor, couldn't find one - it also seems it's not exposed to GDScript right now.

**Comment by Geequlim** [comment]
`Engine.get_singleton('GDScriptLanguageProtocol').get_workspace().generate_script_api('res://main.gd')`

**Comment by NathanLovato** [comment]
Ah, that's why I couldn't find it! Thank you :)

**Comment by NathanLovato** [comment]
Got it working! Is there a way to collect the `description` key from the source code directly? Without that I still have to parse every file a second time from python to collect docstrings.

```json
{
    "constants": [],
    "description": "",
    "extends_class": ["GSTGroupBehavior"],
    "extends_file": "",
    "icon": "",
...
}
```

**Comment by Geequlim** [comment]
What is the description key ？

Nathan Lovato <notifications@github.com>于2020年1月28日 周二23:21写道：

**Comment by Razoric480** [comment]
It should be the docstring for the class itself. It works for functions and properties, but this code:
```c
get_symbol_defined_at_line(LINE_NUMBER_TO_INDEX(p_class->line))
```

seems to be returning null in `dump_class_api`, which means the class doesn't have documentation.

**Comment by Geequlim** [comment]
What is the script content look like?

Francois Belair <notifications@github.com>于2020年1月29日 周三00:30写道：

**Comment by Razoric480** [comment]
```ruby
extends Reference
class_name GSTPath
# Represents a path made up of Vector3 waypoints, split into path segments for use by path
# following behaviors.


# Whether the path is a loop, or has its start and end disconnected and open ended
var open: bool
# The length of the full path
var length: float


# Creates a path with the provided waypoints
func create_path(waypoints: Array) -> void:
	pass
```

truncated. the parser returns the docstring for the function and the members, but not the class.

**Comment by NathanLovato** [comment]
Ah that's why I wasn't getting any `description` for the scripts I tested! They only have a class docstring.

**Comment by Geequlim** [comment]
You'd better move the documentation to the top.

**Comment by Geequlim** [comment]
Here is an example
https://github.com/GodotExplorer/gdutils/blob/master/utils/RandomPool.gd

**Comment by Razoric480** [comment]
No change - Dictionary.description is still empty.

**Comment by Razoric480** [comment]
LINE_NUMBER_TO_INDEX is the passed line number, -1. The ClassNode's `line` variable is not modified, and so comes up to 0. So it tries to pass in -1 as an index, which is illegal, and so returns null.

It is impossible right now for classes to have a docstring recognized.

**Comment by NathanLovato** [comment]
I also have one or more GDScript files that crash the parser. We're moving to a new apartment in a few hours so I'll have to debug later, but I'll open a bug on the godot repo in a while.

**Comment by NathanLovato** [comment]
@Razoric480 is the class docstring bug something you could fix? If so, you can do it as part of your work for GDQuest, and open an issue and a PR on the godotengine repo

**Comment by Razoric480** [comment]
I'll give it a poke, sure.

**Comment by Geequlim** [comment]
By the way the docstring can be markdown or bbcode we are using in the class documentation xml files for C++ classes

**Comment by Razoric480** [comment]
Okay, so apparently, changing a script file does not recache its contents for the GDScript server until you close and reload the project, at least not with class_name loaded files.

Turns out, that having the docstring as the first line of a GDScript does, in fact, get put into the description key of the output.

```json
"name": "GSTPath",
  "path": "res://src/GSTPath.gd",
  "extends_class": [
    "Reference"
  ],
  "extends_file": "",
  "icon": "",
  "signature": "class GSTPath",
  "description": " Represents a path made up of Vector3 waypoints, split into path segments for use by path\n following behaviors.\n",
```

```ruby
# Represents a path made up of Vector3 waypoints, split into path segments for use by path
# following behaviors.
extends Reference
class_name GSTPath
```

The question then becomes how to make it an easy to use parser. Could be a TSCN with a simple Node with some exported options (what files to document, output to what file, export template, etc) and a way to trigger the export function which you can import into your project. Might make it a bit user friendlier that way than a command line argument.

Or an EditorPlugin.

Since it requires a tool script to get the language protocol, we can't just use the -s argument and run it as a command line script.

**Comment by NathanLovato** [comment]
@Razoric480 I already made an EditorScript, with the instructions: https://github.com/GDQuest/gdscript-docs-maker/tree/master/godot-scripts

**Comment by NathanLovato** [comment]
For now it's fine by me to generate the docs that way, if we happen to do it so much we could use a plugin, it won't take long to add some bit of interface for it and turn it into a package.

**Comment by Razoric480** [comment]
Noted. I did post [an issue](https://github.com/godotengine/godot/issues/35672) and PR for a related crashing bug, though.
