### ISSUE TITLE
Add support for linking to other classes

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/gdscript-docs-maker#15]
The tool generates a flat list of markdown files. As we have all the class and markdown data, we could cross-reference other classes, methods, and properties when generating the reference.

Similar to the Godot reference: http://docs.godotengine.org/en/latest/classes/class_kinematicbody.html-l

**Comment by NathanLovato** [comment]
What should be the markup for that? The Godot class reference uses square brackets, i.e. [method_in_this_class], [ClassName], and [ClassName.method] respectively. Should we use the same for consistency?

**Comment by Razoric480** [comment]
I'm not sure I see what you mean regarding [square brackets], as I can't find any. I thought you meant at the source level, but the docs use
```
:ref:`Name<class_ClassName>`
```

That said, just going [create_path], [GSAIPath], and [GSAIPath.create_path] does sound pretty simple. So long as we remember to add a space if we intend on then wrapping some follow-up texts in parenthesis.

**Comment by NathanLovato** [comment]
Okay let's try that. Anyway it's easy to change before releasing the update.
