### ISSUE TITLE
Add a tagging system

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/gdscript-docs-maker#18]
We currently have a Virtual tag to mark virtual functions, but we could use some more tags. Some ideas:

- Marking deprecated features
- Marking removed features (e.g. having an outdated function greyed out?, with a version number)
- Indicating renamed functions and aliases, along with the version
- Indicating experimental or beta features

Possible markup:

```# tags: virtual, deprecated```

**Comment by Razoric480** [comment]
The current placeholder in _get_methods does not seem to pick up the virtual tag

```markdown
# Returns a number of neighbors based on a `callback` function.
#
# `_find_neighbors` calls `callback` for each agent in the `agents` array that lie within
# the radius around the owning agent and adds one to the count if its `callback` returns true.
# 
# virtual
func _find_neighbors(callback: FuncRef) -> int:
```

Am I using it wrong or is the python code in the wrong?

**Comment by NathanLovato** [comment]
The python code is certainly wrong here, I'll check that right away

**Comment by Razoric480** [comment]
I think I figured it out.
`"description":" Callback for the proximity to call when finding neighbors. Adds `neighbor`'s position\n to the center of mass of the group.\n virtual\n"`

But the python looks to [-1], but there's a baked in \n. So virtual is actually the second to last entry.

**Comment by NathanLovato** [comment]
I've already fixed it, gimme a moment to also write virtual in the markdown

**Comment by Razoric480** [comment]
Works great \♥

**Comment by NathanLovato** [comment]
Another use case from #27:

Marking the constructor of a class as a constructor, i.e., `_init`? I'm not sure if we need a tag for that, but I was thinking you may want to document _init and _ready at times, and maybe other functions that could be part of the initialization of your object?

**Comment by Razoric480** [comment]
Yeah. This could be especially important for systems that, for example, spawn nodes in the scene tree, or modify other already existing nodes. Would be things like that to keep aware as a Godot developer.

**Comment by Razoric480** [comment]
Another tag could be a directory path, instead of dropping everything in one lump
`path:Behaviors/Individual`

Would be nice - it'd work pretty well with github's wiki system.
