### ISSUE TITLE
Remove empty sections from generated markdown documents

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/gdscript-docs-maker#19]
It makes a document rather dense. A particularly egregious example:

# GSTUtils #

**Extends:** 

## Description ##

Math and vector utility functions.

## Methods ##

Type | Name
 --- | --- 

## Method Descriptions ##

**Comment by NathanLovato** [comment]
In the official docs I think they are there even if empty, but I don't mind making them optional

**Comment by Razoric480** [comment]
Though in Godot, if you check Node2D for example, it does not have a signals header.

A toggle flag/option on the python script, maybe.

**Comment by NathanLovato** [comment]
I'm on it now, just gotta fix one last type error
