### ISSUE TITLE
_init with parameters should be included as part of the methods

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/gdscript-docs-maker#27]
The reasoning is that if someone is to call .new(), Godot will only complain about the wrong number of arguments, but not what those arguments should be. Can't exactly rely on intellisense to document our code for us.

**Comment by Razoric480** [comment]
Should it be listed as `new(` to be explicit about why it's listed? And maybe strip the `-> void` from it.

But it could be explicitly listed as a Constructor.

**Comment by NathanLovato** [comment]
That's in part where we can use that tagging system. I'll add it as an entry in #18
