### ISSUE TITLE
Generate a table of contents file

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/gdscript-docs-maker#29]
Create an index.md or _index.md file that gives a TOC and links to the classes in the reference: once converted to html:

```markdown
# Project name: version

Project description

* Base Types
  - [[GSTAgentLocation]]
  - [[GSTSteeringAgent]]
  - [[GSTTargetAcceleration]]
  - [[GSTPath]]
  - [[GSTUtils]]
* Individual Behaviors
  - [[GSTSteeringBehavior]]
  - [[GSTSeek]]
  - [[GSTFlee]]
  - [[GSTArrive]]
  - [[GSTPursue]]
  - [[GSTEvade]]
  - [[GSTMatchOrientation]]
  - [[GSTFace]]
  - [[GSTLookWhereYouGo]]
  - [[GSTFollowPath]]
* Group Behaviors
  - [[GSTGroupBehavior]]
  - [[GSTAvoidCollisions]]
  - [[GSTCohesion]]
  - [[GSTSeparation]]
* Combination Behaviors
  - [[GSTBlend]]
  - [[GSTPriority]]
* Proximities
  - [[GSTProximity]]
  - [[GSTRadiusProximity]]
  - [[GSTInfiniteProximity]]

```

Even if you remove the categories, it would already look a lot better than the wiki's Pages dropdown, and we could introduce formatting options.

**Comment by NathanLovato** [comment]
I was thinking of relying on Hugo for that. Putting the docs on the website, we have much more flexibility than using the wiki, and for the user the experience is much nicer (instant search etc.) - also, wikis are per repo, while on the website we can have all our tools and manuals in one place.

So I'd rather let someone else contribute that kind of feature.

**Comment by NathanLovato** [comment]
The main project info is already available since the last commit. See the `ProjectInfo` type.

For categories, I think we need to add support for a new piece of metadata. It'll be much easier to handle from the code and cleaner in the source markup as well:
```gdscript
# docstring
# category: Base behaviors
# tags: ai, steering
class_name GSAIFlee
....
```

Part of the reason is that there's no way to know what we could use tags for in the future, or which tag should be the class's category.

**Comment by Razoric480** [comment]
Yeah, that makes sense. And it keeps us from doing something ugly like needing to support parameterized tags like `category:base types`

**Comment by NathanLovato** [comment]
The data side is ready, all that's left is to add a module or functions to write the index page.

**Comment by NathanLovato** [comment]
Some more notes:

- The hugo format should probably output a different index page or none at all. Instead, we could add a key in the front matter of the class pages to give full control over the index page and rendering.
- The index page should be optional maybe? Either with a `--make-index` or `--make-toc` command line flag? Or should this be generated by default and suppresed with `--no-index`?

**Comment by Razoric480** [comment]
I think I'd make it opt-in instead of opt-out, so --make-index.

**Comment by NathanLovato** [comment]
Done with d14cfd8590a1d0113bb77f0f30d4caa650993569
The categories should work but I didn't take the time to test them thoroughly.

**Comment by Razoric480** [comment]
I'll give it a shot!

**Comment by Razoric480** [comment]
```

## Contents ##

- [GSAIUtils](GSAIUtils.md)
- **Base types**
  - [GSAIAgentLocation](GSAIAgentLocation.md)
  - [GSAIGroupBehavior](GSAIGroupBehavior.md)
  - [GSAIPath](GSAIPath.md)
  - [GSAISteeringAgent](GSAISteeringAgent.md)
  - [GSAISteeringBehavior](GSAISteeringBehavior.md)
  - [GSAITargetAcceleration](GSAITargetAcceleration.md)
- **Combination behaviors**
  - [GSAIBlend](GSAIBlend.md)
  - [GSAIPriority](GSAIPriority.md)
- **Group behaviors**
  - [GSAIAvoidCollisions](GSAIAvoidCollisions.md)
  - [GSAICohesion](GSAICohesion.md)
  - [GSAISeparation](GSAISeparation.md)
- **Individual behaviors**
  - [GSAIArrive](GSAIArrive.md)
  - [GSAIEvade](GSAIEvade.md)
  - [GSAIFace](GSAIFace.md)
  - [GSAIFlee](GSAIFlee.md)
  - [GSAIFollowPath](GSAIFollowPath.md)
  - [GSAILookWhereYouGo](GSAILookWhereYouGo.md)
  - [GSAIMatchOrientation](GSAIMatchOrientation.md)
  - [GSAIPursue](GSAIPursue.md)
  - [GSAISeek](GSAISeek.md)
- **Proximities**
  - [GSAIInfiniteProximity](GSAIInfiniteProximity.md)
  - [GSAIProximity](GSAIProximity.md)
  - [GSAIRadiusProximity](GSAIRadiusProximity.md)
- **Specialized agents**
  - [GSAIKinematicBody2DAgent](GSAIKinematicBody2DAgent.md)
  - [GSAIKinematicBody3DAgent](GSAIKinematicBody3DAgent.md)
  - [GSAIRigidBody2DAgent](GSAIRigidBody2DAgent.md)
  - [GSAIRigidBody3DAgent](GSAIRigidBody3DAgent.md)
  - [GSAISpecializedAgent](GSAISpecializedAgent.md)
```

Looks sexy!
