### ISSUE TITLE
Static/virtual tag formatting

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/gdscript-docs-maker#31]
### angle\_to\_vector2 ###

`**static** func angle_to_vector2(angle: float) -> Vector2`

Returns a directional vector from the given orientation angle.
 
 This assumes orientation for 2D agents or 3D agents that are upright and
 rotate around the Y axis.

---

Is this the intended format? It makes the asterisks look a little superfluous, or like an error in formatting. Though on the flip side, without the code block, this makes the signature blend in.

---

### angle\_to\_vector2 ###

**static** func angle_to_vector2(angle: float) -> Vector2

Returns a directional vector from the given orientation angle.
 
 This assumes orientation for 2D agents or 3D agents that are upright and
 rotate around the Y axis.

---

What about a quote with `> `?

---

### angle\_to\_vector2 ###

> **static** func angle_to_vector2(angle: float) -> Vector2

Returns a directional vector from the given orientation angle.
 
 This assumes orientation for 2D agents or 3D agents that are upright and
 rotate around the Y axis.

---

**Comment by NathanLovato** [comment]
We can also use html if need be. Like, have it in the title.

<hr>

## <small>virtual</small> angle_to_vector2 ##

```gdscript
func angle_to_vector2(angle: float) -> Vector2
```
Returns a directional vector from the given orientation angle.

This assumes orientation for 2D agents or 3D agents that are upright and
rotate around the Y-axis.

<hr>

**Comment by NathanLovato** [comment]
To clarify, I wanted to use code tags for code highlighting, it helps with reading. Our website and github both support GDScript
