### ISSUE TITLE
Static functions still use inline code blocks for signatures

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/gdscript-docs-maker#32]
Current output:
## vector3_to_angle (static) ##

`func vector3_to_angle(vector: Vector3) -> float`

**Comment by NathanLovato** [comment]
What's the issue? That it doesn't show the static keyword?

**Comment by Razoric480** [comment]
The signature is using an inline, rather than a language formatted code block.

It's currently:
\`func vector3_to_angle(vector: Vector3) -> float\`

It should probably be:
\```gdscript
func vector3_to_angle(vector: Vector3) -> float
\```

**Comment by NathanLovato** [comment]
Thanks, it's fixed
