### ISSUE TITLE
On Windows, must have the json as first argument or else it is considered an invalid argument

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/gdscript-docs-maker#39]
---
Fails:
```cmd
λ gdscript_docs_maker --format markdown -p godot-steering-ai-framework ../godot-steering-ai-framework/project/reference.json
usage: GDScript Docs Maker [-h] [-p PATH] [-f FORMAT] [-d DATE] [-a AUTHOR]
                           [-v] [--dry-run]
                           files [files ...]
GDScript Docs Maker: error: unrecognized arguments: ../godot-steering-ai-framework/project/reference.json
```
---
Succeeds:
```cmd
E:\Projects\Games\GDQuest\gdscript-docs-maker (master -> origin)
λ gdscript_docs_maker ../godot-steering-ai-framework/project/reference.json --format markdown -p godot-steering-ai-framework

λ 
```
---

**Comment by NathanLovato** [comment]
It's on every platform, the files argument comes first. I had put that positional argument first.

**Comment by NathanLovato** [comment]
Regardless of the way I change the arguments, positional arguments always have to come first with Python's argparse module it seems. We could use argv or the remainder of arguments to get files, but that would mean losing the automated docs - I don't think it's too big of a deal to have to put the json file first.

Closing for now, if it's important to you, we can reopen.
