### ISSUE TITLE
Script generate_reference does not work in Debian/Linux

### ISSUE THREAD

**Issue by Pskalou** [GDQuest/gdscript-docs-maker#57]
Hello every body, and thank's for the work !

**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**

Using Debian/Linux, the generate_reference script doesn't work.
I have made these changes at the end of your file :
1. first changing
`python3 -m gdscript_docs_maker "$($godot_project_dir)/reference.json"`
by this one
`python3 -m gdscript_docs_maker "$godot_project_dir/reference.json"` 
2. your output_dir option doesn't copy de .md files in any folders. Also I add this at the end : 
`mv export/* "$output_directory"`

Thanks again for all you did,
cheers, Pskalou

**Comment by NathanLovato** [comment]
I'll have to check, it was working no problem for me.
You shouldn't need to move the files to another directory, gdscript_docs_maker can save in $output_directory directly with the correct flag.

**Comment by NathanLovato** [comment]
Thanks for the report, and PRs are always welcome!

**Comment by NathanLovato** [comment]
Could you give me your traceback/error log?
