### ISSUE TITLE
It doesn't work as it should

### ISSUE THREAD

**Issue by jebedaia360** [GDQuest/gdscript-docs-maker#60]
So I installed gdscript-docs-maker using python pip like you say I should in README.
And Try to run it.
1. My system can find any `generate_reference` so add download it
1. I run it but it fails and generate empty script called _ReferenceCollectorCLI.gd_
1. So I download all your zip find this that there are dir _godot-scripts_ and I need to copy to of them to my project - Why main README don't say about this?
1. I try to run _ReferenceCollector.gd_ , but there are error in at line **29** that `Collector.print_pretty_json()` don't have specified type so I remove `:`
1. I try to run this script again, but there are error at the same line again that `Collector.print_pretty_json()` don't take 2 arguments so I remove `true`
1. I try to run this script again and it works and generete _reference.json_
1. I run `generate_reference`, but now I get this:
```
cat: godot-scripts/ReferenceCollectorCLI.gd: Nie ma takiego pliku ani katalogu
/home/jeremi360/Apps/Scripts/generate_reference: 81: test: !=: unexpected operator
'/tmp/tmp.Xod6Pu56k2' -> './ReferenceCollectorCLI.gd'
cp: nie można wykonać stat na 'godot-scripts/Collector.gd': Nie ma takiego pliku ani katalogu
Generating reference json data...
ERROR: start: Can't load script 'ReferenceCollectorCLI.gd', it does not inherit from a MainLoop type.
   At: main/main.cpp:1585.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2071.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:476.
Done.
usunięty './ReferenceCollectorCLI.gd'
rm: nie można usunąć './Collector.gd': Nie ma takiego pliku ani katalogu
Generating markdown files in export
mkdir: utworzony katalog 'export'
/usr/bin/python3: No module named gdscript_docs_maker
```
And also why it removes _Collector.gd_ now I need to copy it again - it can be frustrating if I want to make a few to times because I saw that I need to fix some thing.

**Comment by jebedaia360** [comment]
When I dowload zip and unzip it, and then from there run script generate_reference.sh it just worked - strange.

**Comment by NathanLovato** [comment]
If you install from pip, you won't get `generate_reference.sh`. You have to clone the repository to use it. I'll add a note in the README to clarify that.
