### ISSUE TITLE
Script did not work, lots of errors

### ISSUE THREAD

**Issue by martinellison** [GDQuest/gdscript-docs-maker#62]
Program did not work. Output was:

> ~/extgit/gdscript-docs-maker> ./generate_reference ~/git/shmup3/exper/gen1/
> ./generate_reference: line 81: test: !=: unary operator expected
> '/home/martin/tmp/tmp.col8Jp4gn5' -> '/home/martin/git/shmup3/exper/gen1/ReferenceCollectorCLI.gd'
> 'godot-scripts/Collector.gd' -> '/home/martin/git/shmup3/exper/gen1/Collector.gd'
> Generating reference json data...
> WARNING: initialize: Error setting locale modifiers
>    At: platform/x11/os_x11.cpp:156.
> WARNING: initialize: XOpenIM failed
>    At: platform/x11/os_x11.cpp:198.
> WARNING: initialize: XCreateIC couldn't create xic
>    At: platform/x11/os_x11.cpp:500.
> The directory does not exist: res://src
> WARNING: _get: Property not found: application/config/version
>    At: core/project_settings.cpp:209.
> ERROR: ~List: Condition "_first != __null" is true.
>    At: ./core/self_list.h:112.
> ERROR: ~List: Condition "_first != __null" is true.
>    At: ./core/self_list.h:112.
> WARNING: cleanup: ObjectDB Instances still exist!
>    At: core/object.cpp:2071.
> ERROR: clear: Resources Still in use at Exit!
>    At: core/resource.cpp:476.
> ERROR: cleanup: There are still MemoryPool allocs in use at exit!
>    At: core/pool_vector.cpp:69.
> Done.
> removed '/home/martin/git/shmup3/exper/gen1/ReferenceCollectorCLI.gd'
> removed '/home/martin/git/shmup3/exper/gen1/Collector.gd'
> Generating markdown files in export
>

**Comment by NathanLovato** [comment]
> The directory does not exist: res://src

You have to indicate the directories to explore to generate docs in Collector.gd or CollectorCLI.gd. by default it's res://src, so it doesn't generate docs for add-ons you might have in your projects.
