### ISSUE TITLE
Support godot <3.1

### ISSUE THREAD

**Issue by quentincaffeino** [GDQuest/gdscript-docs-maker#67]
So I'm developing an add-on which supports 3.0^, where a couple of features not present and some other the features like class_name I don't consider usable yet. I have all the things working inside a `Collector` but maybe it would be better to move them to the python package since Collectors work only to collect.

What I propose is to add:

1. Fulfilling class names based on file name: `src/Collection.gd` -> `class_name Collection`
2. Fixing missing class parents by parsing `extends_file`: `extends "src/Collection.gd"` -> `extends_class: Collection`
3. Add docblocs parser which will be able to fulfill all the missing types (and more) from the docblocks.

Having code like this:

```gdscript
# @deprecated
# @param    String  name
# @returns  Command|null
func getCommand(name):
	return self.get_command(name)
```

Will give this docs:

### ~~getCommand~~ <small>(deprecated)</small>

```gdscript
func getCommand(name: String): Command|null
```

**Comment by NathanLovato** [comment]
I don't want to maintain support for older Godot versions. Actually, Godot 4.0 has native docs generation, and this program is only intended as a transitional package.

If you want to support that yourself and add all the required code + maybe tests, that's fine, but I won't maintain it personally.

**Comment by quentincaffeino** [comment]
Sure, that's understandable.

Didn't know 4.0 will have docs generation.

I thought it would be developed further. If it's just a transitional package then this doesn't matter much an I can just keep having local version for my needs.

Best

**Comment by NathanLovato** [comment]
Looking back and considering how much Godot 4 got delayed, we could have those in here. If you have the code done and you're fine maintaining that portion (there's generally little maintenance on this program), we can get it in.

The only thing to figure out, I think is that by default, the idea was to only generate docs for named classes: only the classes you do want to expose to your API and provide documentation for. So we would need an annotation or something to distinguish files without class names to export from others.

**Comment by quentincaffeino** [comment]
I don't have much time right now, but I would like to share these features so as soon as I'll have time I will get back to it.

**Comment by quentincaffeino** [comment]
> The only thing to figure out, I think is that by default, the idea was to only generate docs for named classes: only the classes you do want to expose to your API and provide documentation for. So we would need an annotation or something to distinguish files without class names to export from others.

I propose putting something like `@docs:export` somewhere in the beginning of the file. However I would need to check if It is possible to parse this somehow ideally without parsing file manually.

**Comment by NathanLovato** [comment]
You mean we need to see if although the class isn't named, the language server registers metadata? If so it should, because as far as I remember you get docstrings and everything for all files in VSCode.

Maybe in the past, it didn't, but I sponsored a teammate to fix various issues and add new features to Godot's language server over the past year. Now it's more reliable and powerful.

**Comment by NathanLovato** [comment]
Note I'm now managing multiple large projects at once, so I have especially limited availability.
