### ISSUE TITLE
Support for nested lists in markdown

### ISSUE THREAD

**Issue by db0** [GDQuest/gdscript-docs-maker#68]
## Feature request ##

I'm trying to write a long docstring which includes explanation for a class. I wanted to use nested unordered lists for better layout, but it doesn't seem to be supported. All my lists are being set  to the "root" indentation.

I'd like to achieve this format

* item a
* item b
   * item b1
   * item b2
* item c

I've tried to indent using both spaces (of various lengths) and tabs.

The only way to work around this limitation to specify just display the parent list like so:

* item a
* item b
* * item b1
* * item b2
* item c

But of course, it looks uglier

**Comment by NathanLovato** [comment]
This happens most likely because the code strips whitespace after the comment starts.
