### ISSUE TITLE
Ignore built-ins and private symbols

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/gdscript-docs-maker#7]
The tool should optionally include or ignore built-in methods such as `_process`, that are not part of a GDScript framework's public API.

Also, the tool should skip private functions. The convention in Godot is that one leading underscore stands for virtual, i.e. a function that you're meant to override. So we could use two leading underscores, i.e. `__symbol`, to mark private methods, subclasses, and properties.

I'd rather stick to one underscore, `_`, as in Python, for private. I think that we can differentiate them from virtual functions if the function either returns or, ideally, passes:

```gdscript
func _virtual_function():
    pass
```

@Razoric480 any thoughts on that?

**Comment by Razoric480** [comment]
For built-in types, there's only so many: _enter_tree, _exit_tree, _input, _physics_process, _process, _ready, _unhandled_input, and _unhandled_key_input. I imagine we can maintain a dictionary for those.

Though virtual VS private is the other niggle. I'd really prefer not having double underscores. I'm already not a fan of how one looks, heh. That said, an API reference will point out functions that are public facing. Simply not adding a docstring to a function should make it essentially-private as far as a documentation generator is concerned.

Then we differentiate a virtual and private function (or a virtual private function) by the mere fact that it is or isn't documented.

**Comment by NathanLovato** [comment]
For builtins yes, I already have the list actually.

> Simply not adding a docstring to a function should make it essentially-private as far as a documentation generator is concerned.

It's too easy to forget a docstring, or to document a function that shouldn't be. We shouldn't rely on us not making mistakes for the tool to work as expected.

It's a pity we don't have a virtual keyword, but at least a virtual function is one that should just `pass`, it shouldn't define any behavior, so I guess we can rely on that, and count the leading underscore as private otherwise.

**Comment by Razoric480** [comment]
Though with typed GDScript and virutla functions that return a value, we can't just pass - if the virtual function returns something, Godot will error out.

```ruby
func _do_check() -> int: #illegal
  pass
```

So it's not something that can be relied upon, unless we make the base virtual function not have a return type until it's overriden in an extended class. We could explicitly tag a function as virtual in the docstring?
