### ISSUE TITLE
Remove newline on extends

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/gdscript-docs-maker#8]
```json
    {
        "GSTPath.gd": {
            "is_tool": false,
            "class_name": "GSTPath",
            "extends": "Reference\n",
            "docstring": [
                "Represents a path made up of Vector3 waypoints, split into path segments for use by path\n",
                "following behaviors.\n"
```

Edit: Extends should probably be more like a class type.

**Comment by NathanLovato** [comment]
What's the issue? The trailing \n? If so, it's not CRLF, it's just that every line in the file as parsed by Python ends with \n. Same on Linux. We should remove them then?

**Comment by Razoric480** [comment]
Oh, I was rereading the example parse on the PR you had written up, and it didn't have them then - I was wondering if it was an issue on my end or because of Windows. My mistake.

While it's fine for docstrings, which could be multiple lines, I don't feel they should be there for extends.
