### ISSUE TITLE
generate-reference.bat fails when folder paths contains whitespaces

### ISSUE THREAD

**Issue by clement-or** [GDQuest/gdscript-docs-maker#82]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**

Running `generate-reference.bat` on windows causes a FileNotFoundError because the file paths is cut.
This happens if the file path contains whitespaces.

**What is the expected behavior?**

Building without a problem

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

* Create a Godot project in a folder named "My Folder" and add the `generate-reference.bat` file
* Run `generate-ref.bat .` or `generate-ref.bat "%cd%"`

I have yet to find a workaround or a fix

**Comment by NathanLovato** [comment]
Thanks for the report. I'll need a windows user to fix this one. I don't use the windows CMD shell at all and wouldn't know how to fix it.

**Comment by clement-or** [comment]
I'll try that and I'll let you know

**Comment by clement-or** [comment]
It seems the issue is now fixed, I'll close it

**Comment by NathanLovato** [comment]
Thanks
