### ISSUE TITLE
Support for license boilerplate text

### ISSUE THREAD

**Issue by kreivi** [GDQuest/gdscript-docs-maker#89]
**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

## Feature request ##

**Describe the problem you're trying to solve.**

Some licenses (such as [GNU General Public License v3.0](https://choosealicense.com/licenses/gpl-3.0/)) suggests to include license information for every source code file in the project. Currently if you include license boilerplate into script files it ends up as description for the class.

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

I tried formatting the license boilerplate text with single `#`, double `##` and `"""` but with every format it seems to end up as class description.

### Solution suggestion ###

In your [guidelines](https://www.gdquest.com/docs/guidelines/best-practices/godot-gdscript/#code-style-and-order) there is a suggestion to have the class docstring starting with double `##`. I would suggest that the class description is picked from the first block that starts with double `##` so one could have boilerplate text/comments on top of the script file without it affecting the class description.

**Comment by NathanLovato** [comment]
The only way we could do that is by detecting and removing those licenses. From Godot 4 that won't be a problem: docstrings will have to start with double hashes. But for now, the language server catches every comment. above some definition.

**Comment by kreivi** [comment]
I see. 

Would it make sense to allow user to give some "processing" instructions to the generator and thus give control for the developer to mark some blocks of comment out? I.e. something like `#gddocs:ignore:start` and `#gddocs:ignore:end` that would ignore everything between those processing instructions.

It's a bit of a workaround for sure and makes the code look little messy with the processing instructions as comments.

I guess it might be just better to implement a script that strips the license or any other boilerplate out before the collector runs and get the description to match with the class docstring.

**Comment by NathanLovato** [comment]
Whichever is fine. You could also remove the licenses with a one-line sed command in the generated documents like

`sed --in-place '1,13d'` deletes the first 13 lines, which corresponds to one version of GPL comments + new line. You could change the range to target exactly where it'll end up, which should be consistent across files.

Or a regex search and replace would do too, something like `sed -iE 's|This file is part of.+If not, see <https://www.gnu.org/licenses/>\.\n||'

**Comment by kreivi** [comment]
This seems like good solution for the problem knowing that Godot 4.0 will change things. The license boilerplate for every file will be exactly same and can be worked around quite easily. I think that this resolved the feature suggestion and it requires no actions thus can be closed.

**Comment by NathanLovato** [comment]
Alright, thanks
